spring.application.name=aegis-backend

server.port=8080

# ===============================
# DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/aegis_db

spring.datasource.username=aegis_user
spring.datasource.password=aegis123



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT
# ===============================

jwt.secret=THIS_IS_SECRET_KEY_FOR_AEGIS_AI_PROJECT

jwt.expiration=86400000
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent